// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmbvQr5jj_st7RcLbNAdBs_zkkGDUFNHw',
    appId: '1:890690734143:web:42eeda24a6a92091e3508a',
    messagingSenderId: '890690734143',
    projectId: 'tourism-f4546',
    authDomain: 'tourism-f4546.firebaseapp.com',
    storageBucket: 'tourism-f4546.appspot.com',
    measurementId: 'G-2MND7SL4MV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjt53PrXG5yXmQsSFNpeuk5GtgroS4LaM',
    appId: '1:890690734143:android:0ccaee415b1e1d5ee3508a',
    messagingSenderId: '890690734143',
    projectId: 'tourism-f4546',
    storageBucket: 'tourism-f4546.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB52ppM7A5XSR5IkxRZ_9X3pI0DjFU096s',
    appId: '1:890690734143:ios:279403659dcebebee3508a',
    messagingSenderId: '890690734143',
    projectId: 'tourism-f4546',
    storageBucket: 'tourism-f4546.appspot.com',
    iosClientId: '890690734143-qoipoq5p572m73b1i2370pr6pl34msck.apps.googleusercontent.com',
    iosBundleId: 'com.example.tourism',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB52ppM7A5XSR5IkxRZ_9X3pI0DjFU096s',
    appId: '1:890690734143:ios:279403659dcebebee3508a',
    messagingSenderId: '890690734143',
    projectId: 'tourism-f4546',
    storageBucket: 'tourism-f4546.appspot.com',
    iosClientId: '890690734143-qoipoq5p572m73b1i2370pr6pl34msck.apps.googleusercontent.com',
    iosBundleId: 'com.example.tourism',
  );
}
